shared: &shared
  docker:
    - image: docker:stable-git
  environment:
    IMAGE_USER: lmmsci
    IMAGE_PREFIX: lmms-ci-
  steps:
    - checkout
    - setup_remote_docker:
        version: 17.05.0-ce
    - run:
        name: Build image
        command: |
          ./build-image.sh $CIRCLE_JOB 14.04
        environment:
          DOCKER_ARGS: "--build-arg UBUNTU_VERSION=14.04"

version: 2
jobs:
  base:
    <<: *shared
  linux:
    <<: *shared
  linux.gcc:
    <<: *shared
  linux.mingw:
    <<: *shared
  linux.mingw32:
    <<: *shared
  linux.mingw64:
    <<: *shared
workflows:
  version: 2
  build_images:
    jobs:
      - base
      - linux:
          requires:
           - base
      - linux.gcc:
          requires:
           - linux
      - linux.mingw:
          requires:
           - base
      - linux.mingw32:
          requires:
           - linux.mingw
      - linux.mingw64:
          requires:
           - linux.mingw
